import type { JSONSchema } from "./workflow-types.js";

export interface VangrexWorkflowSchema {
  id: string;
  name?: string | null;
  inputSchema: JSONSchema | null;
}

/**
 * Convert a JSON Schema into a TypeScript type.
 */
export function jsonSchemaToTypeScript(
  schema: JSONSchema | null,
  indent = 0,
): string {
  if (!schema) {
    return "Record<string, never>";
  }

  switch (schema.type) {
    case "string":
      return "string";

    case "number":
      return "number";

    case "integer":
      return "number";

    case "boolean":
      return "boolean";

    case "null":
      return "null";

    case "array": {
      if (!schema.items) {
        return "unknown[]";
      }

      const itemType = jsonSchemaToTypeScript(schema.items, indent);

      if (itemType.includes("\n")) {
        return `Array<${itemType}>`;
      }

      return `${itemType}[]`;
    }

    case "object":
      return objectSchemaToTypeScript(schema, indent);

    default:
      return "unknown";
  }
}

/**
 * Convert an object JSON Schema into a TypeScript object type.
 */
function objectSchemaToTypeScript(schema: JSONSchema, indent: number): string {
  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? []);

  const entries = Object.entries(properties);

  if (entries.length === 0) {
    if (schema.additionalProperties === false) {
      return "Record<string, never>";
    }

    return "Record<string, unknown>";
  }

  const currentIndent = " ".repeat(indent);
  const propertyIndent = " ".repeat(indent + 2);

  const lines = entries.map(([name, propertySchema]) => {
    const optional = required.has(name) ? "" : "?";

    const propertyName = formatPropertyName(name);

    const type = jsonSchemaToTypeScript(propertySchema, indent + 2);

    return `${propertyIndent}${propertyName}${optional}: ${type};`;
  });

  return ["{", ...lines, `${currentIndent}}`].join("\n");
}

/**
 * Format a JSON property name as valid TypeScript.
 */
function formatPropertyName(name: string): string {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) {
    return name;
  }

  return JSON.stringify(name);
}

/**
 * Escape a string for use as a TypeScript string literal.
 */
function escapeString(value: string): string {
  return JSON.stringify(value);
}

/**
 * Generate the complete Vangrex workflow contract.
 */
export function generateWorkflowTypes(
  workflows: VangrexWorkflowSchema[],
): string {
  const workflowEntries = workflows
    .map((workflow) => {
      const inputType = jsonSchemaToTypeScript(workflow.inputSchema, 4);

      return [
        `  ${escapeString(workflow.id)}: {`,
        `    input: ${inputType};`,
        "  };",
      ].join("\n");
    })
    .join("\n\n");

  return `// This file is generated by Vangrex.
// Do not edit this file manually.

import type { WorkflowMap } from "@vangrex/sdk";

export interface VangrexWorkflows extends WorkflowMap {
${workflowEntries}
}
`;
}
