import type { WorkflowMap } from "./workflow-types.js";

/**
 * Extract the input type for a workflow.
 */
export type WorkflowInput<
  TWorkflows extends WorkflowMap,
  TWorkflowId extends keyof TWorkflows,
> = TWorkflows[TWorkflowId]["input"];

/**
 * A workflow contract generated by Vangrex.
 *
 * This interface is intentionally empty.
 *
 * Users/generator output augment it with their actual workflows.
 */
export interface VangrexWorkflows extends WorkflowMap {}
